
# server port: 8888 ??
server:
  port: 8888


spring:
  application:
    name: config-server
  # git Repository yml
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/maruduke/msa-config-repo"
          basedir: StompChat
          search-paths: dev


management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/  # eureka server 명시



